github: TomsProject
patreon: ztp
open_collective: pt
ko_fi: tomsproject
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: tomsproject
otechie: stp
